### ISSUE TITLE
mark-up for text regions that appear vertical

### ISSUE THREAD

**Issue by SpitzbartAnna** [emt-project/emt-transkribus-export#4]
So far I added <add place="top left vertical-tb" to text regions that are placed vertically on the page. Since we have the coordinates of the regions already in the xml-files, can we use this somehow? There are a few letters, where the empress ran out of space on the last page and just scribbled on at the first page somewhere - how do I approach this to make sure that the reader knows that and it is clear even without the image?

eg. 45_8_0009
Lev suggested something along the lines of this (just a prompt, still would have to check proper mark-up according to the TEI guidelines):

```
<p facs="#facs_9_region_1591703084085_123" type="irregular" place="top left" text-orientation="vertical-tb" remark="Die beiden Zeilen wurden vertikal angefügt.">
   <lb n="N001"/>Ihr Mayestät der verwitibte Kayserin schmekt auch der rodenfelder käs gahr
   <lb n="N002"/>wohl, aber mit taratuflen in öhl. Bin fro, das nit mit mues eßen.
</p>
```

**Comment by SpitzbartAnna** [comment]
I checked the guidelines for a more accurate approach -would this work:

`<p facs="#facs_9_region_1591703084085_123">
               <lb n="N001"/><style= "writing mode: vertical-tb"><note type="editorische Anmerkung">Die beiden Zeilen wurden vertikal angefügt.</note>Ihr Mayestät der verwitibte Kayserin schmekt auch der rodenfelder käs gahr</style>`

We already have the information about the location of the text region from Transkribus, we only need the indication of writing mode and writing direction, I think?

**Comment by csae8092** [comment]
we won't use the coordiantes to display the added text accordingly to the coordinates on the html page because
* this is really really cumbersome to implement
* makes it hard to read for the user
* and we publish the faksimiles anyways literary next to the transcribed text

we can mark those paragraphs graphically (e.g. some light background color) and display the  text from the notes (maybe together with the information from the `style`element as e.g. a special kind of footnote
